---
  - name: Configuring full-fledged CT services
    include_tasks: 07-1-fullctsrv.yml
    when: full_ct_server

  - name: Configuring minimal CT service
    include_tasks: 07-2-testctsrv.yml
    when: not full_ct_server
